name: deploy
on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.17.0"
          rebar3-version: "3"

      - name: Build app
        run: cd app && gleam run -m lustre/dev build --minify --outdir=dist

      - name: Fix app.js path for GitHub Pages
        run: sed -i 's|/app.js|/html-lustre-converter/app.js|g' app/dist/index.html

      - name: Fix app.css path for GitHub Pages
        run: sed -i 's|/app.css|/html-lustre-converter/app.css|g' app/dist/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "app/dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
